const { Sequelize, Model, DataTypes } = require("sequelize");
const employee = require("./employee");
/*const sequelize = new Sequelize("mssql::memory:");*/


const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST,
    dialect: process.env.DB_DIALECT,
  }
);


const Journal_sahra_importer = sequelize.define("Journal_sahra_importer", {

        id_tran:
        {
                autoIncrement: true,
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true
        },



        job: DataTypes.STRING(500),
   


        id_emp: {
                type: DataTypes.INTEGER,
                references: {
                    model: employee, // 'Movies' would also work
                    key: 'ID_EMP'
                }
            },


        j_1: DataTypes.STRING(5),
        j_2: DataTypes.STRING(5),
        j_3: DataTypes.STRING(5),
        j_4: DataTypes.STRING(5),
        j_5: DataTypes.STRING(5),
        j_6: DataTypes.STRING(5),
        j_7: DataTypes.STRING(5),
        j_8: DataTypes.STRING(5),
        j_9: DataTypes.STRING(5),
        j_10: DataTypes.STRING(5),
        j_12: DataTypes.STRING(5),
        j_13: DataTypes.STRING(5),
        j_14: DataTypes.STRING(5),
        j_15: DataTypes.STRING(5),
        j_16: DataTypes.STRING(5),
        j_17: DataTypes.STRING(5),
        j_18: DataTypes.STRING(5),
        j_19: DataTypes.STRING(5),
        j_20: DataTypes.STRING(5),
        j_21: DataTypes.STRING(5),
        j_22: DataTypes.STRING(5),
        j_23: DataTypes.STRING(5),
        j_24: DataTypes.STRING(5),
        j_25: DataTypes.STRING(5),
        j_26: DataTypes.STRING(5),
        j_27: DataTypes.STRING(5),
        j_28: DataTypes.STRING(5),
        j_29: DataTypes.STRING(5),
        j_30: DataTypes.STRING(5),
        j_31: DataTypes.STRING(5),
        j_11: DataTypes.STRING(5),
        DATE_JS: DataTypes.DATE,
        invesstissment_no: DataTypes.INTEGER,
        nom: DataTypes.STRING(100),
        Comment: DataTypes.STRING(100),
        nbr_h: DataTypes.INTEGER,
        nbr_jour: DataTypes.INTEGER,
        nbr_maladie: DataTypes.INTEGER,
        IS_ERROR: DataTypes.BOOLEAN,
        nbrj_emission_sahra: DataTypes.INTEGER,
        NBR_HS: DataTypes.INTEGER,
        IS_FOREG: DataTypes.BOOLEAN,
        E1: DataTypes.DATE,
        E2: DataTypes.DATE,
        E3: DataTypes.DATE,
        E4: DataTypes.DATE,
        E5: DataTypes.DATE,
        E6: DataTypes.DATE,
        E7: DataTypes.DATE,
        E8: DataTypes.DATE,
        E9: DataTypes.DATE,
        E10: DataTypes.DATE,
        E11: DataTypes.DATE,
        E12: DataTypes.DATE,
        E13: DataTypes.DATE,
        E14: DataTypes.DATE,
        E15: DataTypes.DATE,
        E16: DataTypes.DATE,
        E17: DataTypes.DATE,
        E18: DataTypes.DATE,
        E19: DataTypes.DATE,
        E20: DataTypes.DATE,
        E21: DataTypes.DATE,
        E22: DataTypes.DATE,
        E23: DataTypes.DATE,
        E24: DataTypes.DATE,
        E25: DataTypes.DATE,
        E26: DataTypes.DATE,
        E27: DataTypes.DATE,
        E28: DataTypes.DATE,
        E29: DataTypes.DATE,
        E30: DataTypes.DATE,
        E31: DataTypes.DATE,
        S1: DataTypes.DATE,
        S2: DataTypes.DATE,
        S3: DataTypes.DATE,
        S4: DataTypes.DATE,
        S5: DataTypes.DATE,
        S6: DataTypes.DATE,
        S7: DataTypes.DATE,
        S8: DataTypes.DATE,
        S9: DataTypes.DATE,
        S10: DataTypes.DATE,
        S11: DataTypes.DATE,
        S12: DataTypes.DATE,
        S13: DataTypes.DATE,
        S14: DataTypes.DATE,
        S15: DataTypes.DATE,
        S16: DataTypes.DATE,
        S17: DataTypes.DATE,
        S18: DataTypes.DATE,
        S19: DataTypes.DATE,
        S20: DataTypes.DATE,
        S21: DataTypes.DATE,
        S22: DataTypes.DATE,
        S23: DataTypes.DATE,
        S24: DataTypes.DATE,
        S25: DataTypes.DATE,
        S26: DataTypes.DATE,
        S27: DataTypes.DATE,
        S28: DataTypes.DATE,
        S29: DataTypes.DATE,
        S30: DataTypes.DATE,
        S31: DataTypes.DATE,
        COMMENTAIRE_FINAL: DataTypes.STRING(200),
        is_negative: DataTypes.BOOLEAN,
        DATE_FINAL: DataTypes.DATEONLY,
        ID_EMPRINT: DataTypes.BOOLEAN,
        j_abscence: DataTypes.FLOAT,
        t_retart: DataTypes.FLOAT,
        classe: DataTypes.STRING(500),
        missing: DataTypes.BOOLEAN,
        NATIONAL_NO: DataTypes.STRING(50),
        IN_CALL: DataTypes.STRING(50),
        L_P: DataTypes.INTEGER,
        END_CNTR: DataTypes.STRING(50),
        R_1: DataTypes.STRING(5),
        R_2: DataTypes.STRING(5),
        R_3: DataTypes.STRING(5),
        R_4: DataTypes.STRING(5),
        R_5: DataTypes.STRING(5),
        R_6: DataTypes.STRING(5),
        R_7: DataTypes.STRING(5),
        R_8: DataTypes.STRING(5),
        R_9: DataTypes.STRING(5),
        R_10: DataTypes.STRING(5),
        R_11: DataTypes.STRING(5),
        R_12: DataTypes.STRING(5),
        R_13: DataTypes.STRING(5),
        R_14: DataTypes.STRING(5),
        R_15: DataTypes.STRING(5),
        R_16: DataTypes.STRING(5),
        R_17: DataTypes.STRING(5),
        R_18: DataTypes.STRING(5),
        R_19: DataTypes.STRING(5),
        R_20: DataTypes.STRING(5),
        R_21: DataTypes.STRING(5),
        R_22: DataTypes.STRING(5),
        R_23: DataTypes.STRING(5),
        R_24: DataTypes.STRING(5),
        R_25: DataTypes.STRING(5),
        R_26: DataTypes.STRING(5),
        R_27: DataTypes.STRING(5),
        R_28: DataTypes.STRING(5),
        R_29: DataTypes.STRING(5),
        R_30: DataTypes.STRING(5),
        R_31: DataTypes.STRING(5),
        ID_DEL: DataTypes.BOOLEAN,
        IS_OK: {
                type: DataTypes.BOOLEAN,
                allowNull: false
        },
        Day_Chift_nbr: DataTypes.INTEGER,
        Night_Shift_nbr: DataTypes.INTEGER,
        Other_Shift_nbr: DataTypes.INTEGER,
        bonus_hakli_nbr: DataTypes.INTEGER
        ,
}, {
        freezeTableName: true,
        timestamps: false,
});

module.exports = sequelize.model("Journal_sahra_importer", Journal_sahra_importer);
