const { Sequelize, Model, DataTypes } = require("sequelize");
const employee = require("./employee");
/*const sequelize = new Sequelize("mssql::memory:");*/


const sequelize = new Sequelize('FC_NAGECO', 'sa', '123', {
    dialect: 'mssql'


});

const Journal_sahra_importer = sequelize.define("Journal_sahra_importer", {

    id_tran:
    {
        autoIncrement: true,
        type: DataTypes.BIGINT,
        allowNull: false,
        primaryKey: true
    },



    job: DataTypes.TEXT,
   


    id_emp: {
        type: DataTypes.INTEGER,
        references: {
          model: employee, // 'Movies' would also work
          key: 'ID_EMP'
        }
      },


    j_1: DataTypes.TEXT,
    j_2: DataTypes.TEXT,
    j_3: DataTypes.TEXT,
    j_4: DataTypes.TEXT,
    j_5: DataTypes.TEXT,
    j_6: DataTypes.TEXT,
    j_7: DataTypes.TEXT,
    j_8: DataTypes.TEXT,
    j_9: DataTypes.TEXT,
    j_10: DataTypes.TEXT,
    j_12: DataTypes.TEXT,
    j_13: DataTypes.TEXT,
    j_14: DataTypes.TEXT,
    j_15: DataTypes.TEXT,
    j_16: DataTypes.TEXT,
    j_17: DataTypes.TEXT,
    j_18: DataTypes.TEXT,
    j_19: DataTypes.TEXT,
    j_20: DataTypes.TEXT,
    j_21: DataTypes.TEXT,
    j_22: DataTypes.TEXT,
    j_23: DataTypes.TEXT,
    j_24: DataTypes.TEXT,
    j_25: DataTypes.TEXT,
    j_26: DataTypes.TEXT,
    j_27: DataTypes.TEXT,
    j_28: DataTypes.TEXT,
    j_29: DataTypes.TEXT,
    j_30: DataTypes.TEXT,
    j_31: DataTypes.TEXT,
    j_11: DataTypes.TEXT,
    DATE_JS: DataTypes.DATE,
    invesstissment_no: DataTypes.INTEGER,
    nom: DataTypes.TEXT,
    Comment: DataTypes.TEXT,
    nbr_h: DataTypes.INTEGER,
    nbr_jour: DataTypes.INTEGER,
    nbr_maladie: DataTypes.INTEGER,
    IS_ERROR: DataTypes.BOOLEAN,
    nbrj_emission_sahra: DataTypes.INTEGER,
    NBR_HS: DataTypes.INTEGER,
    IS_FOREG: DataTypes.INTEGER,
    E1: DataTypes.DATE,
    E2: DataTypes.DATE,
    E3: DataTypes.DATE,
    E4: DataTypes.DATE,
    E5: DataTypes.DATE,
    E6: DataTypes.DATE,
    E7: DataTypes.DATE,
    E8: DataTypes.DATE,
    E9: DataTypes.DATE,
    E10: DataTypes.DATE,
    E11: DataTypes.DATE,
    E12: DataTypes.DATE,
    E13: DataTypes.DATE,
    E14: DataTypes.DATE,
    E15: DataTypes.DATE,
    E16: DataTypes.DATE,
    E17: DataTypes.DATE,
    E18: DataTypes.DATE,
    E19: DataTypes.DATE,
    E20: DataTypes.DATE,
    E21: DataTypes.DATE,
    E22: DataTypes.DATE,
    E23: DataTypes.DATE,
    E24: DataTypes.DATE,
    E25: DataTypes.DATE,
    E26: DataTypes.DATE,
    E27: DataTypes.DATE,
    E28: DataTypes.DATE,
    E29: DataTypes.DATE,
    E30: DataTypes.DATE,
    E31: DataTypes.DATE,
    S1: DataTypes.DATE,
    S2: DataTypes.DATE,
    S3: DataTypes.DATE,
    S4: DataTypes.DATE,
    S5: DataTypes.DATE,
    S6: DataTypes.DATE,
    S7: DataTypes.DATE,
    S8: DataTypes.DATE,
    S9: DataTypes.DATE,
    S10: DataTypes.DATE,
    S11: DataTypes.DATE,
    S12: DataTypes.DATE,
    S13: DataTypes.DATE,
    S14: DataTypes.DATE,
    S15: DataTypes.DATE,
    S16: DataTypes.DATE,
    S17: DataTypes.DATE,
    S18: DataTypes.DATE,
    S19: DataTypes.DATE,
    S20: DataTypes.DATE,
    S21: DataTypes.DATE,
    S22: DataTypes.DATE,
    S23: DataTypes.DATE,
    S24: DataTypes.DATE,
    S25: DataTypes.DATE,
    S26: DataTypes.DATE,
    S27: DataTypes.DATE,
    S28: DataTypes.DATE,
    S29: DataTypes.DATE,
    S30: DataTypes.DATE,
    S31: DataTypes.DATE,
    COMMENTAIRE_FINAL: DataTypes.TEXT,
    is_negative: DataTypes.BOOLEAN,
    DATE_FINAL: DataTypes.DATE,
    ID_EMPRINT: DataTypes.BOOLEAN,
    j_abscence: DataTypes.INTEGER,
    t_retart: DataTypes.INTEGER,
    classe: DataTypes.TEXT,
    missing: DataTypes.BOOLEAN,
    NATIONAL_NO: DataTypes.TEXT,
    IN_CALL: DataTypes.TEXT,
    L_P: DataTypes.INTEGER,
    END_CNTR: DataTypes.TEXT,
    R_1: DataTypes.TEXT,
    R_2: DataTypes.TEXT,
    R_3: DataTypes.TEXT,
    R_4: DataTypes.TEXT,
    R_5: DataTypes.TEXT,
    R_6: DataTypes.TEXT,
    R_7: DataTypes.TEXT,
    R_8: DataTypes.TEXT,
    R_9: DataTypes.TEXT,
    R_10: DataTypes.TEXT,
    R_11: DataTypes.TEXT,
    R_12: DataTypes.TEXT,
    R_13: DataTypes.TEXT,
    R_14: DataTypes.TEXT,
    R_15: DataTypes.TEXT,
    R_16: DataTypes.TEXT,
    R_17: DataTypes.TEXT,
    R_18: DataTypes.TEXT,
    R_19: DataTypes.TEXT,
    R_20: DataTypes.TEXT,
    R_21: DataTypes.TEXT,
    R_22: DataTypes.TEXT,
    R_23: DataTypes.TEXT,
    R_24: DataTypes.TEXT,
    R_25: DataTypes.TEXT,
    R_26: DataTypes.TEXT,
    R_27: DataTypes.TEXT,
    R_28: DataTypes.TEXT,
    R_29: DataTypes.TEXT,
    R_30: DataTypes.TEXT,
    R_31: DataTypes.TEXT,
    ID_DEL: DataTypes.BOOLEAN,
    IS_OK: DataTypes.BOOLEAN,
    Day_Chift_nbr: DataTypes.INTEGER,
    Night_Shift_nbr: DataTypes.INTEGER,
    Other_Shift_nbr: DataTypes.INTEGER,
    bonus_hakli_nbr: DataTypes.INTEGER
    ,
}, {
    freezeTableName: true,
    timestamps: false,
});

module.exports = sequelize.model("Journal_sahra_importer", Journal_sahra_importer);
